### PR TITLE
 [FEAT] Renamed Client/Server headings #165 

### LINKED ISSUE #164: [BUG] MODS - Server client - Bad Phrasing
@jupster 
In the current state, the `Profile/Mods/` Table has the collumn `Server` and `Client` which are reffering to the `-server="..."` and `-mods="..."` Parameters. 

As of now, they are **massively missleading** for anyone who is not already familiar with those parameters.

grafik

PLEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWWWSEEEEEEE FIX

The following Mockup shows a way to make it so much more intuitive even for the common pleb who doesnt know what he is doing.
`Only Server` & `Client + Server`

faster-mockup

### PR DESCRIPTION
**Pull request by liamcannon**
Closes #164 

## Motivation and Context

- Clears confusion for how a mod is loaded on the server
- Updated tool tips
- Updated Column headers to abbreviations

## How Has This Been Tested?
- Launch Faster
- Open Server profile
- Tested on 1.9

## Screenshots (if appropriate):
image

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by jupster** [comment]
Changes broke right click drop downs (Ref photo) from Server and Client column. 

image

**Comment by liamcannon** [comment]
> Changes broke right click drop downs (Ref photo) from Server and Client column.
> 
> image
> 
> Check `FASTER/Models/ServerProfile.cs`, `FASTER/ViewModel/ProfileViewModel.cs`, `FASTER/Views/Profile.xaml` & `FASTER/Views/Profile.xaml.cs`

Resolved in recent commit

**Review by jupster — CHANGES_REQUESTED** [review]
[FASTER/Views/Profile.xaml](https://github.com/Foxlider/FASTER/pull/166/files#diff-7a323735df6118e94bc1303b9fe7d7ece840f3dbdbf61df95fa11bc661d94ba3R109-R166) These where missed in the rest of the renaming. 

Probably wait till https://discord.com/channels/366955806777671681/602087451279884298/1205073058927484949 has gotten a decision made.

**Comment by liamcannon** [comment]
I started to add the updated headers w/ the linebreak and implemented it like this. But realized it breaks the right click menu. You guys have any thoughts on a better way to do it?

` <DataGridTemplateColumn Width="auto">
     <DataGridTemplateColumn.Header>
         <TextBlock TextWrapping="Wrap">
             <Run Text="SERVER +" />
             <LineBreak />
             <Run Text="CLIENT" />           
         </TextBlock>
     </DataGridTemplateColumn.Header>
     <DataGridTemplateColumn.CellTemplate>
         <DataTemplate DataType="models:ProfileMod">
             <CheckBox IsChecked="{Binding ClientSideChecked, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" HorizontalAlignment="Center"/>
         </DataTemplate>
     </DataGridTemplateColumn.CellTemplate>
 </DataGridTemplateColumn>`

**Comment by liamcannon** [comment]
Current thing on hold is best way to implement the text stacking without breaking right click. Spoke with Jupster a few days ago and they said they'd take a peak. Solution above breaks because its using the text box instead of `Header="Server Only` in the `DataGridTemplateColumn`

**Review by jupster — COMMENTED** [review]
From doing a quick look over it all seemed working and good. I think it would be best to use

`Server Only | Server + Client | HC | OPT`

**Review by jupster — APPROVED** [review]

**Review by jupster — APPROVED** [review]

**Pull request merged**
