### PR TITLE
Added a custom string[] for TacticalPing in ProfileCfgArrays.

### PR DESCRIPTION
**Pull request by Jasperdoit**
## Description
I've added a string[] that adds additional options to the TacticalPing profile option. These options include:
[0] = Disabled
[1] = Deprecated
[2] = Exclude Map
[3] = Enabled

## Motivation and Context
The reason for this change is because of a hidden detail about the tactical ping parameter. When the option is assigned one or two, it will ONLY show up inside the 3D view of the game. You will not be able to view the tactical ping on the map unless you set TacticalPing to three. This change hopes to bring clarity to this hidden detail and provide comfort and insight for the user.

## How Has This Been Tested?
I've compiled the code and opened the application. From there, I navigated to the difficulty tab of one of my server profiles. When there, I selected option 0 (disabled) after which I saved the change. Along side that, I opened up the profile file that corrosponds to that server. The value mirrored the expected result. This was tested for all options available in the difficulty drop-down, all of which gave an expected result.

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Jasperdoit** [comment]
Pardon for the faulty screenshot, I meant to send the following: 
image

**Comment by Foxlider** [comment]
Are you sure that Arma supports multiple values in the Profile.cfg for TacticalPing ?
https://community.bistudio.com/wiki/Arma_3:_Server_Profile
https://community.bistudio.com/wiki/Arma_3:_Difficulty_Settings

Also if it is a valid setting, maybe "Deprecated" value should be removed because it seems confusing

**Review by Foxlider — CHANGES_REQUESTED** [review]
Aso, never ever commit directly on `master` branch. 
You have to merge to `feature/Update-x.y`

**Comment by jupster** [comment]
From Arma Wiki today

```
0 is disabled
1 is in 3D scene only, but not on map
2 is on map, but not in 3D scene
3 is both
```

**Comment by jupster** [comment]
Merged in https://github.com/Foxlider/FASTER/pull/155

**Pull request closed without merging**
